#!/usr/bin/env bash
# bstack postinstall — wire control harness into the workspace.
#
# Run as part of the clone + `bstack bootstrap` flow (bstack is a CLI/substrate, not
# a skills.sh skill — do NOT `npx skills add broomva/bstack`, it drops bin/scripts).
# Activates the governance layer: git hooks, Claude Code hooks, conversation bridge,
# and policy.
#
# Usage: bash scripts/postinstall.sh [TARGET_DIR]
#   TARGET_DIR defaults to the git repo root or $HOME/broomva

set -e

# ── Resolve target workspace ──────────────────────────────────────────────────
TARGET="${1:-$(git rev-parse --show-toplevel 2>/dev/null || echo "$HOME/broomva")}"

if [ ! -d "$TARGET" ]; then
  echo "[error] Target directory not found: $TARGET"
  exit 1
fi

echo "========================================="
echo "  bstack postinstall — wiring control harness"
echo "  Target: $TARGET"
echo "========================================="
echo ""

PASS=0
CREATED=0

# ── 1. Governance files ──────────────────────────────────────────────────────
echo "1. Governance Files"

ensure_file() {
  local file="$1" desc="$2"
  if [ -f "$TARGET/$file" ]; then
    echo "  [ok] $file (exists)"
    PASS=$((PASS + 1))
  else
    echo "  [create] $file — $desc"
    CREATED=$((CREATED + 1))
  fi
}

ensure_file "CLAUDE.md" "workspace invariants"
ensure_file "AGENTS.md" "agent operational rules"
ensure_file "METALAYER.md" "control-systems manifest"

# Create .control/policy.yaml if missing
mkdir -p "$TARGET/.control"
if [ -f "$TARGET/.control/policy.yaml" ]; then
  echo "  [ok] .control/policy.yaml (exists)"
  PASS=$((PASS + 1))
else
  cat > "$TARGET/.control/policy.yaml" << 'POLICY'
# bstack Control Policy — generated by postinstall
version: "1.0"
profile: governed

setpoints:
  - id: S10
    name: "bstack_skills_installed"
    target: 24
    alert_below: 24
    measurement: "make bstack-check skill count"
    severity: blocking

  - id: S11
    name: "governance_files_present"
    target: 5
    alert_below: 5
    measurement: "CLAUDE.md + AGENTS.md + METALAYER.md + .control/policy.yaml + schemas/"
    severity: blocking

  - id: S12
    name: "hooks_wired"
    target: 3
    alert_below: 3
    measurement: "pre-commit + Stop hook + PreToolUse gate"
    severity: blocking

gates:
  hard:
    - id: G1
      rule: "No force push to main/master"
      pattern: "git push.*--force.*(main|master)"
    - id: G2
      rule: "No destructive git reset"
      pattern: "git reset --hard"
    - id: G3
      rule: "No rm -rf on home/root"
      pattern: "rm -rf\\s+(~/|/Users/|/)"
    - id: G4
      rule: "No committing secrets"
      pattern: "\\.(env|env\\.local|credentials\\.json)$"
  soft:
    - id: G5
      rule: "Prefer feature branches over direct main commits"
    - id: G6
      rule: "Run make check before pushing"
POLICY
  echo "  [create] .control/policy.yaml"
  CREATED=$((CREATED + 1))
fi
echo ""

# ── 2. Git pre-commit hook ───────────────────────────────────────────────────
echo "2. Git Hooks"

mkdir -p "$TARGET/.githooks"
if [ -x "$TARGET/.githooks/pre-commit" ]; then
  echo "  [ok] .githooks/pre-commit (exists)"
  PASS=$((PASS + 1))
else
  cat > "$TARGET/.githooks/pre-commit" << 'HOOK'
#!/bin/bash
# pre-commit — bstack control gate
set -e
REPO="$(git rev-parse --show-toplevel)"
echo "=== bstack pre-commit gate ==="

# Governance files check
FAIL=0
for f in CLAUDE.md AGENTS.md METALAYER.md .control/policy.yaml; do
  [ ! -f "$REPO/$f" ] && echo "  [FAIL] Missing: $f" && FAIL=1
done
[ $FAIL -eq 0 ] && echo "  [ok] Governance files present"

# Secrets check
SECRETS=$(git diff --cached --name-only | grep -E '\.(env|env\.local|env\.production|credentials\.json|service-account\.json)$' || true)
if [ -n "$SECRETS" ]; then
  echo "  [FAIL] Secrets staged: $SECRETS"
  exit 1
fi
echo "  [ok] No secrets staged"

# Conversation bridge auto-index
if git diff --cached --name-only | grep -q '^docs/conversations/' 2>/dev/null; then
  if [ -f "$REPO/scripts/conversation-history.py" ] && command -v python3 >/dev/null 2>&1; then
    echo "  [info] Regenerating conversation index..."
    (cd "$REPO" && python3 scripts/conversation-history.py 2>/dev/null) || true
    git add docs/conversations/Conversations.md 2>/dev/null || true
  fi
fi

echo "=== pre-commit gate passed ==="
HOOK
  chmod +x "$TARGET/.githooks/pre-commit"
  echo "  [create] .githooks/pre-commit"
  CREATED=$((CREATED + 1))
fi

# Wire git hooks path
CURRENT_HOOKS_PATH=$(cd "$TARGET" && git config core.hooksPath 2>/dev/null || echo "")
if [ "$CURRENT_HOOKS_PATH" = ".githooks" ]; then
  echo "  [ok] git hooks path = .githooks"
  PASS=$((PASS + 1))
else
  (cd "$TARGET" && git config core.hooksPath .githooks)
  echo "  [wire] git config core.hooksPath .githooks"
  CREATED=$((CREATED + 1))
fi
echo ""

# ── 3. Claude Code hooks ─────────────────────────────────────────────────────
echo "3. Claude Code Hooks"

CLAUDE_SETTINGS="$TARGET/.claude/settings.json"
mkdir -p "$TARGET/.claude"

# Create control-gate-hook if missing
if [ ! -f "$TARGET/scripts/control-gate-hook.sh" ]; then
  mkdir -p "$TARGET/scripts"
  cat > "$TARGET/scripts/control-gate-hook.sh" << 'GATE'
#!/bin/bash
# control-gate-hook.sh — Claude Code PreToolUse safety shield
# Reads gates dynamically from .control/policy.yaml

EVENT=$(cat)
TOOL_NAME=$(echo "$EVENT" | python3 -c "import sys,json; print(json.load(sys.stdin).get('tool_name',''))" 2>/dev/null || echo "")

if [ "$TOOL_NAME" = "Bash" ]; then
  COMMAND=$(echo "$EVENT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('tool_input',{}).get('command',''))" 2>/dev/null || echo "")
  CMD_LEN=${#COMMAND}

  if [ "$CMD_LEN" -lt 500 ]; then
    REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || echo "")
    POLICY="$REPO_ROOT/.control/policy.yaml"

    if [ -f "$POLICY" ] && command -v python3 >/dev/null 2>&1; then
      RESULT=$(python3 -c "
import yaml, re, sys
try:
    with open('$POLICY') as f:
        policy = yaml.safe_load(f)
    cmd = sys.stdin.read()
    for gate in policy.get('gates', {}).get('hard', []):
        pattern = gate.get('pattern', '')
        if pattern and re.search(pattern, cmd):
            print(f'{gate[\"id\"]}: {gate[\"rule\"]}')
            sys.exit(0)
except Exception:
    pass
" <<< "$COMMAND" 2>/dev/null)

      if [ -n "$RESULT" ]; then
        GATE_ID=$(echo "$RESULT" | cut -d: -f1)
        REASON=$(echo "$RESULT" | cut -d: -f2-)
        echo "{\"decision\": \"block\", \"reason\": \"Safety shield $GATE_ID:$REASON\"}"
        exit 0
      fi
    else
      # Fallback: hardcoded gates if no policy.yaml or no PyYAML
      if echo "$COMMAND" | grep -qE 'git push.*--force.*(main|master)'; then
        echo '{"decision": "block", "reason": "Safety shield G1: force push to main/master blocked"}'
        exit 0
      fi
      if echo "$COMMAND" | grep -qE 'git reset --hard'; then
        echo '{"decision": "block", "reason": "Safety shield G2: git reset --hard blocked"}'
        exit 0
      fi
      if echo "$COMMAND" | grep -qE 'rm -rf\s+(~/|/Users/|/)'; then
        echo '{"decision": "block", "reason": "Safety shield G3: destructive rm -rf blocked"}'
        exit 0
      fi
    fi
  fi
fi

exit 0
GATE
  chmod +x "$TARGET/scripts/control-gate-hook.sh"
  echo "  [create] scripts/control-gate-hook.sh"
  CREATED=$((CREATED + 1))
else
  echo "  [ok] scripts/control-gate-hook.sh (exists)"
  PASS=$((PASS + 1))
fi

# Create conversation bridge hook if missing
if [ ! -f "$TARGET/scripts/conversation-bridge-hook.sh" ]; then
  cat > "$TARGET/scripts/conversation-bridge-hook.sh" << 'BRIDGE'
#!/bin/bash
# conversation-bridge-hook.sh — Claude Code Stop hook for conversation tracing
set -e
cat > /dev/null 2>&1 || true
STAMP_FILE="${HOME}/.cache/broomva-bridge-stamp"
COOLDOWN=120
if [ -f "$STAMP_FILE" ]; then
  if [ "$(uname)" = "Darwin" ]; then
    last_run=$(stat -f %m "$STAMP_FILE" 2>/dev/null || echo 0)
  else
    last_run=$(stat -c %Y "$STAMP_FILE" 2>/dev/null || echo 0)
  fi
  elapsed=$(( $(date +%s) - last_run ))
  [ "$elapsed" -lt "$COOLDOWN" ] && exit 0
fi
mkdir -p "$(dirname "$STAMP_FILE")"
touch "$STAMP_FILE"
REPO="$(git rev-parse --show-toplevel 2>/dev/null || echo "")"
if [ -n "$REPO" ] && [ -f "$REPO/scripts/conversation-history.py" ] && command -v python3 >/dev/null 2>&1; then
  (cd "$REPO" && python3 scripts/conversation-history.py >> "${HOME}/.cache/broomva-bridge.log" 2>&1) &
  disown
fi
exit 0
BRIDGE
  chmod +x "$TARGET/scripts/conversation-bridge-hook.sh"
  echo "  [create] scripts/conversation-bridge-hook.sh"
  CREATED=$((CREATED + 1))
else
  echo "  [ok] scripts/conversation-bridge-hook.sh (exists)"
  PASS=$((PASS + 1))
fi

# Create regression gate hook if missing
if [ ! -f "$TARGET/scripts/regression-gate-hook.sh" ]; then
  echo "  [create] scripts/regression-gate-hook.sh"
  cat > "$TARGET/scripts/regression-gate-hook.sh" << 'RGATE'
#!/bin/bash
# regression-gate-hook.sh — Claude Code PreToolUse hook for E2E regression testing.
# Intercepts git commit, analyzes staged files against regression-test-map.json,
# and prompts Claude to run agent-browser E2E tests for affected features.

EVENT=$(cat)
TOOL_NAME=$(echo "$EVENT" | python3 -c "import sys,json; print(json.load(sys.stdin).get('tool_name',''))" 2>/dev/null || echo "")
[ "$TOOL_NAME" = "Bash" ] || exit 0

COMMAND=$(echo "$EVENT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('tool_input',{}).get('command',''))" 2>/dev/null || echo "")
echo "$COMMAND" | grep -qE '^\s*git commit' || exit 0
echo "$COMMAND" | grep -qE '\-\-amend|\-\-allow-empty' && exit 0

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || echo "")
[ -n "$REPO_ROOT" ] || exit 0
TEST_MAP="$REPO_ROOT/scripts/regression-test-map.json"
[ -f "$TEST_MAP" ] || exit 0

# Check bypass stamp (10 min TTL)
STAMP="$HOME/.cache/broomva-regression-stamp"
if [ -f "$STAMP" ]; then
  if [ "$(uname)" = "Darwin" ]; then
    AGE=$(( $(date +%s) - $(stat -f %m "$STAMP") ))
  else
    AGE=$(( $(date +%s) - $(stat -c %Y "$STAMP") ))
  fi
  [ "$AGE" -lt 600 ] && exit 0
fi

# Skip if [skip-regression] in commit message
echo "$COMMAND" | grep -q '\[skip-regression\]' && exit 0

RESULT=$(python3 -c "
import json, fnmatch, subprocess, sys
staged = subprocess.check_output(['git', 'diff', '--cached', '--name-only'], cwd='$REPO_ROOT', text=True).strip().split('\n')
staged = [f for f in staged if f]
if not staged: sys.exit(0)
with open('$TEST_MAP') as f:
    m = json.load(f)
affected = {}
for name, feat in m.get('features', {}).items():
    for p in feat.get('patterns', []):
        for f in staged:
            if fnmatch.fnmatch(f, p) or fnmatch.fnmatch(f, '*/' + p):
                if name not in affected:
                    affected[name] = {'url': feat.get('url',''), 'scenarios': feat.get('scenarios',[]), 'files': []}
                if f not in affected[name]['files']:
                    affected[name]['files'].append(f)
if not affected: sys.exit(0)
lines = ['Regression tests needed. Affected features:', '']
for n, i in affected.items():
    lines.append(f'**{n}** ({len(i[\"files\"])} files)')
    [lines.append(f'  - {f}') for f in i['files'][:5]]
    lines.append(f'  URL: {i[\"url\"]}')
    lines.append('  Scenarios:')
    [lines.append(f'    - {s}') for s in i['scenarios']]
    lines.append('')
lines.append('Run E2E regression tests via agent-browser before committing.')
lines.append('To skip: include [skip-regression] in commit message.')
print('\n'.join(lines))
" 2>/dev/null)

if [ -n "$RESULT" ]; then
  ESCAPED=$(echo "$RESULT" | python3 -c "import sys,json; print(json.dumps(sys.stdin.read()))" 2>/dev/null)
  echo "{\"decision\": \"ask\", \"message\": $ESCAPED}"
  exit 0
fi
exit 0
RGATE
  chmod +x "$TARGET/scripts/regression-gate-hook.sh"
  CREATED=$((CREATED + 1))
else
  echo "  [ok] scripts/regression-gate-hook.sh (exists)"
  PASS=$((PASS + 1))
fi

# Create regression test map if missing
if [ ! -f "$TARGET/scripts/regression-test-map.json" ]; then
  echo "  [create] scripts/regression-test-map.json (empty template)"
  cat > "$TARGET/scripts/regression-test-map.json" << 'TESTMAP'
{
  "_doc": "Maps file-path glob patterns to feature areas and E2E test scenarios.",
  "features": {}
}
TESTMAP
  CREATED=$((CREATED + 1))
else
  echo "  [ok] scripts/regression-test-map.json (exists)"
  PASS=$((PASS + 1))
fi

# Wire Claude Code settings.json if it doesn't have hooks
if [ -f "$CLAUDE_SETTINGS" ]; then
  if grep -q "conversation-bridge-hook" "$CLAUDE_SETTINGS" 2>/dev/null; then
    echo "  [ok] .claude/settings.json hooks wired"
    PASS=$((PASS + 1))
  else
    echo "  [warn] .claude/settings.json exists but hooks not wired — manual update needed"
  fi
else
  cat > "$CLAUDE_SETTINGS" << SETTINGS
{
  "hooks": {
    "Stop": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "$TARGET/scripts/conversation-bridge-hook.sh",
            "timeout": 5
          }
        ]
      }
    ],
    "Notification": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "$TARGET/scripts/conversation-bridge-hook.sh",
            "timeout": 5
          }
        ]
      }
    ],
    "PreToolUse": [
      {
        "matcher": "Bash",
        "hooks": [
          {
            "type": "command",
            "command": "$TARGET/scripts/control-gate-hook.sh",
            "timeout": 5
          },
          {
            "type": "command",
            "command": "$TARGET/scripts/regression-gate-hook.sh",
            "timeout": 10
          }
        ]
      }
    ]
  }
}
SETTINGS
  echo "  [create] .claude/settings.json with hooks"
  CREATED=$((CREATED + 1))
fi
echo ""

# ── 4. Status line ────────────────────────────────────────────────────────────
echo "4. Status Line"

STATUSLINE_SRC="$(cd "$(dirname "$0")" && pwd)/statusline-command.sh"
STATUSLINE_DST="$HOME/.claude/statusline-command.sh"

# Install statusline script
if [ -f "$STATUSLINE_SRC" ]; then
  if [ -f "$STATUSLINE_DST" ] && diff -q "$STATUSLINE_SRC" "$STATUSLINE_DST" >/dev/null 2>&1; then
    echo "  [ok] statusline-command.sh (up to date)"
    PASS=$((PASS + 1))
  else
    cp "$STATUSLINE_SRC" "$STATUSLINE_DST"
    chmod +x "$STATUSLINE_DST"
    echo "  [install] statusline-command.sh → ~/.claude/"
    CREATED=$((CREATED + 1))
  fi
else
  echo "  [warn] statusline-command.sh not found in bstack/scripts/"
fi

# Wire statusLine into user-level settings (~/.claude/settings.json)
USER_SETTINGS="$HOME/.claude/settings.json"
if [ -f "$USER_SETTINGS" ]; then
  if grep -q '"statusLine"' "$USER_SETTINGS" 2>/dev/null; then
    echo "  [ok] statusLine wired in ~/.claude/settings.json"
    PASS=$((PASS + 1))
  else
    # Inject statusLine config into existing settings.json using jq
    if command -v jq >/dev/null 2>&1; then
      TMP=$(mktemp)
      jq --arg cmd "$STATUSLINE_DST" '. + {"statusLine": {"type": "command", "command": $cmd}}' "$USER_SETTINGS" > "$TMP" && mv "$TMP" "$USER_SETTINGS"
      echo "  [wire] statusLine added to ~/.claude/settings.json"
      CREATED=$((CREATED + 1))
    else
      echo "  [warn] jq not found — add statusLine to ~/.claude/settings.json manually"
    fi
  fi
else
  echo "  [skip] ~/.claude/settings.json not found (project-level only)"
fi
echo ""

# ── 5. Summary ───────────────────────────────────────────────────────────────
echo "========================================="
echo "  Postinstall complete"
echo "  Existing: $PASS | Created: $CREATED"
if [ "$CREATED" -gt 0 ]; then
  echo "  Control harness activated with $CREATED new artifacts"
else
  echo "  Control harness already fully wired"
fi
echo "========================================="

# ── 6. First-time setup hint ─────────────────────────────────────────────────
# If the init marker is missing, the user hasn't run the onboarding wizard
# on this machine. Hint them at it — don't auto-invoke since postinstall
# runs non-interactively as part of `npx skills add`, and the wizard
# expects either user prompts or agent-driven AskUserQuestion for inputs.
BSTACK_MARKER="${BROOMVA_STATE_DIR:-$HOME/.config/broomva/bstack}/initialized"
ONBOARD_SH="$(dirname "$0")/onboard.sh"
if [ ! -f "$BSTACK_MARKER" ]; then
  echo ""
  echo "  ─── First-time setup detected ─────────────────"
  echo "  bstack hasn't been onboarded on this machine yet."
  echo ""
  echo "  In Claude Code: open a session — the bstack preamble"
  echo "                  will guide you through the wizard."
  echo "  In a shell:     bash $ONBOARD_SH"
  echo "  ───────────────────────────────────────────────"
  echo ""
fi
