// The token-name manifest — the machine-readable map from Tailwind v4 `@theme
// inline` names to the design-system CSS variables (TOKENS-INTEGRATION §3).
//
// This is the source of truth for the @theme block; `buildThemeCss()` emits the
// CSS from it, and `dist/manifest.json` is its JSON projection. The `--bv-*`
// names are verified against the actual token source (spacing.css / typography.css
// / colors.css) — TOKENS-INTEGRATION §3's example text uses `--bv-radius-input`
// and `--bv-radius-row`, but the source (spacing.css) defines `--bv-radius-md`
// and `--bv-radius-lg`; §3 line 81 says the source files win, so this manifest
// follows the source.

/** A Tailwind @theme group → { theme-suffix: css-var-name }. */
export interface ThemeTokens {
  /** Emitted as `--color-<key>: var(<value>)`. */
  colors: Record<string, string>;
  /** Emitted as `--radius-<key>: var(<value>)`. */
  radius: Record<string, string>;
  /** Emitted as `--text-<key>: var(<value>)`. */
  text: Record<string, string>;
  /** Emitted as `--font-<key>: var(<value>)`. */
  font: Record<string, string>;
}

/**
 * The manifest. Colors map onto the shadcn semantic layer (colors.css); the one
 * raw accent (`blue`) is exposed for status/glow/links used sparingly. Radii,
 * text, and fonts map to the `--bv-*` primitives (spacing.css / typography.css).
 * The type scale is **closed**: 12/14/16/18/22/24/28 (no text-3xl, no one-offs).
 */
export const THEME_TOKENS: ThemeTokens = {
  colors: {
    background: "--background",
    foreground: "--foreground",
    card: "--card",
    "card-foreground": "--card-foreground",
    primary: "--primary",
    "primary-foreground": "--primary-foreground",
    secondary: "--secondary",
    "secondary-foreground": "--secondary-foreground",
    muted: "--muted",
    "muted-foreground": "--muted-foreground",
    accent: "--accent",
    "accent-foreground": "--accent-foreground",
    border: "--border",
    input: "--input",
    ring: "--ring",
    sidebar: "--sidebar",
    // the one accent — status/glow/links, used sparingly
    blue: "--bv-blue",
  },
  radius: {
    chip: "--bv-radius-chip", // 0.25rem
    input: "--bv-radius-md", // 0.375rem  (source name, not --bv-radius-input)
    row: "--bv-radius-lg", // 0.5rem    (source name, not --bv-radius-row)
    card: "--bv-radius-xl", // 0.75rem
    dialog: "--bv-radius-2xl", // 1rem
    composer: "--bv-radius-composer", // 28px
  },
  text: {
    xs: "--bv-text-xs", // 12
    sm: "--bv-text-sm", // 14
    base: "--bv-text-base", // 16
    lg: "--bv-text-lg", // 18
    xl: "--bv-text-xl", // 22
    "2xl": "--bv-text-2xl", // 24
    h1: "--bv-text-h1", // 28
  },
  font: {
    sans: "--bv-font-sans",
    mono: "--bv-font-mono",
    display: "--bv-font-display",
  },
};

/** The Tailwind @theme prefix for each manifest group. */
const GROUP_PREFIX = {
  colors: "--color",
  radius: "--radius",
  text: "--text",
  font: "--font",
} as const;

/**
 * Emit the `@theme inline { … }` block (TOKENS-INTEGRATION §3) from a manifest.
 * Imported into the app's root CSS *after* `@import "tailwindcss"` so utilities
 * like `bg-background`, `text-muted-foreground`, `rounded-card` resolve.
 */
export function buildThemeCss(tokens: ThemeTokens = THEME_TOKENS): string {
  const lines: string[] = [
    "/* Generated by @maestro/tokens — do not edit. Source: THEME_TOKENS manifest. */",
    "@theme inline {",
  ];
  for (const [group, prefix] of Object.entries(GROUP_PREFIX)) {
    const entries = tokens[group as keyof ThemeTokens];
    lines.push(`  /* ${group} */`);
    for (const [key, cssVar] of Object.entries(entries)) {
      lines.push(`  ${prefix}-${key}: var(${cssVar});`);
    }
  }
  lines.push("}", "");
  return lines.join("\n");
}
